### ISSUE TITLE
can't deploy on heroku

### ISSUE THREAD

**Issue by bloblink** [GoByeBye/DiscoSniper#1]
Hi Daddie0 ,
im trying to deploy this repo to heroku but not work
please tell me what is exact buildpack or env values & procfile command for autostart on run dyno
or if it's possible make 'deploy to heroku' button on repo to easy deploy to cpaas like heroku
waiting for your response
finest regards

**Comment by GoByeBye** [comment]
Working on adding it

**Comment by GoByeBye** [comment]
It should be fixed now. Remember you have to edit some variables yourself to make it deploy properly
